### ISSUE TITLE
Elm default imports

### ISSUE THREAD

**Issue by andys8** [alpacaaa/elm-to-purescript-cheatsheet#2]
What a great read! Thanks a lot.

A minor thing I noticed is that Elm default imports focus on the `Basics` module. In fact there is imported much more by default which isn't clear in the text.

https://github.com/elm-lang/core/blob/master/README.md

```elm

import Basics exposing (..)
import List exposing ( List, (::) )
import Maybe exposing ( Maybe( Just, Nothing ) )
import Result exposing ( Result( Ok, Err ) )
import String
import Tuple

import Debug

import Platform exposing ( Program )
import Platform.Cmd as Cmd exposing ( Cmd )
import Platform.Sub as Sub exposing ( Sub )
```

How about adding the link in a half sentence to make this clear?

**Comment by alpacaaa** [comment]
Hey Andy, thanks for pointing that out!

Would the changes in [this commit](https://github.com/alpacaaa/elm-to-purescript-cheatsheet/commit/a9be6e7d814922f836932b8a70bc03793d45bdcd) make it a bit more clear? 😃

**Comment by andys8** [comment]
Awesome. Thanks for integrating the information.
